quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "We can only see a short distance ahead, but we can see plenty there that needs to be done. - Alan Turing",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Dream big and dare to fail. - Norman Vaughan",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Act as if what you do makes a difference. It does. - William James",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Great things are done by a series of small things brought together. - Vincent Van Gogh",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Don't stop when you're tired. Stop when you're done. - Unknown",
    "Wake up with determination. Go to bed with satisfaction. - Unknown",
    "Do something today that your future self will thank you for. - Unknown",
    "Little things make big days. - Unknown",
    "It’s going to be hard, but hard does not mean impossible. - Unknown",
    "Don’t wait for opportunity. Create it. - Unknown",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. - Unknown",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "Dream it. Believe it. Build it. - Unknown",
    "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
    "A river cuts through rock, not because of its power, but because of its persistence. - Jim Watkins",
    "Energy and persistence conquer all things. - Benjamin Franklin",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. - Unknown",
    "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. - Steve Jobs",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. - Mohnish Pabrai",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
    "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
    "We generate fears while we sit. We overcome them by action. - Dr. Henry Link",
    "Whether you think you can or think you can’t, you’re right. - Henry Ford",
    "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
    "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Creativity is intelligence having fun. - Albert Einstein",
    "What you lack in talent can be made up with desire, hustle and giving 110% all the time. - Don Zimmer",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "Develop an 'attitude of gratitude'. Say thank you to everyone you meet for everything they do for you. - Brian Tracy",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "To see what is right and not do it is a lack of courage. - Confucius",
    "Reading is to the mind, as exercise is to the body. - Brian Tracy",
    "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality. - Brian Tracy",
    "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded. - Jack Canfield",
    "Things work out best for those who make the best of how things work out. - John Wooden",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time. - Michael Phelps",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals. - Michelle Obama",
    "Today’s accomplishments were yesterday’s impossibilities. - Robert H. Schuller",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "If you tell the truth, you don't have to remember anything. - Mark Twain",
    "A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "We accept the love we think we deserve. - Stephen Chbosky",
    "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
    "We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde",
    "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. - Neil Gaiman",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bil Keane",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "The opposite of love is not hate, it's indifference. - Elie Wiesel",
    "A lack of transparency results in distrust and a deep sense of insecurity. - Dalai Lama",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "If you can't explain it to a six year old, you don't understand it yourself. - Albert Einstein",
    "It is never too late to be what you might have been. - George Eliot",
    "Everything you can imagine is real. - Pablo Picasso",
    "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "When you want something, all the universe conspires in helping you to achieve it. - Paulo Coelho",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "Pain is inevitable. Suffering is optional. - Haruki Murakami",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost"
    "Victory belongs to the most persevering. - Napoleon Bonaparte",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "If you look at what you have in life, you'll always have more. - Oprah Winfrey",
    "If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey",
    "You may say I'm a dreamer, but I'm not the only one. - John Lennon",
    "To handle yourself, use your head; to handle others, use your heart. - Eleanor Roosevelt",
    "Whatever you are, be a good one. - Abraham Lincoln",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier. - Mother Teresa",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart. - Helen Keller",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Whoever is happy will make others happy too. - Anne Frank",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "You will face many defeats in life, but never let yourself be defeated. - Maya Angelou",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    "Never let the fear of striking out keep you from playing the game. - Babe Ruth",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Many of life's failures are people who did not realize how close they were to success when they gave up. - Thomas A. Edison",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose. - Dr. Seuss",
    "If life were predictable it would cease to be life, and be without flavor. - Eleanor Roosevelt",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Get busy living or get busy dying. - Stephen King",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Love the life you live. Live the life you love. - Bob Marley",
    "Live in the sunshine, swim the sea, drink the wild air. - Ralph Waldo Emerson",
    "The unexamined life is not worth living. - Socrates",
    "Turn your wounds into wisdom. - Oprah Winfrey",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success. - James Cameron",
    "Don't judge each day by the harvest you reap but by the seeds that you plant. - Robert Louis Stevenson",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn. - Benjamin Franklin",
    "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
    "I alone cannot change the world, but I can cast a stone across the waters to create many ripples. - Mother Teresa",
    "Nothing is impossible, the word itself says 'I'm possible'! - Audrey Hepburn",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination. - Jimmy Dean",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Too many of us are not living our dreams because we are living our fears. - Les Brown",
    "Whatever the mind of man can conceive and believe, it can achieve. - Napoleon Hill",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. - Mark Twain",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
    "The most common way people give up their power is by thinking they don't have any. - Alice Walker",
    "The most difficult thing is the decision to act, the rest is merely tenacity. - Amelia Earhart",
    "It is amazing what you can accomplish if you do not care who gets the credit. - Harry S. Truman",
    "The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work. - Oprah Winfrey",
    "If you're offered a seat on a rocket ship, don't ask what seat! Just get on. - Sheryl Sandberg",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank",
    "Some people want it to happen, some wish it would happen, others make it happen. - Michael Jordan",
    "Great things are done by a series of small things brought together. - Vincent Van Gogh",
    "If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward. - Martin Luther King Jr.",
    "I didn't fail the test. I just found 100 ways to do it wrong. - Benjamin Franklin",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
    "There are no traffic jams on the extra mile. - Zig Ziglar",
    "I would rather die of passion than of boredom. - Vincent van Gogh",
    "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
    "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "Winning isn't everything, but wanting to win is. - Vince Lombardi",
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "Dream big and dare to fail. - Norman Vaughan",
    "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "It always seems impossible until it's done. - Nelson Mandela",
    "If you do what you've always done, you'll get what you've always gotten. - Tony Robbins",
    "Dreaming, after all, is a form of planning. - Gloria Steinem",
    "It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live. - Mae Jemison",
    "You may be disappointed if you fail, but you are doomed if you don't try. - Beverly Sills",
    "Remember that not getting what you want is sometimes a wonderful stroke of luck. - Dalai Lama",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. - Barack Obama",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "We can't help everyone, but everyone can help someone. - Ronald Reagan",
    "Nothing will work unless you do. - Maya Angelou",
    "I think beauty comes from knowing who you actually are. - Ellen DeGeneres",
    "Integrity is doing the right thing, even when no one is watching. - C.S. Lewis",
    "Be kind, for everyone you meet is fighting a hard battle. - Plato",
    "We rise by lifting others. - Robert Ingersoll",
    "Attitude is a little thing that makes a big difference. - Winston Churchill",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "Life shrinks or expands in proportion to one's courage. - Anais Nin",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "Believing you are unworthy of love and belonging is the only thing that keeps you from it. - Brené Brown",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "We make a living by what we get, but we make a life by what we give. - Winston Churchill",
    "Happiness depends upon ourselves. - Aristotle",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Honesty is the first chapter in the book of wisdom. - Thomas Jefferson",
    "Knowledge speaks, but wisdom listens. - Jimi Hendrix",
    "The powerful play goes on, and you may contribute a verse. - Walt Whitman",
    "Tough times never last, but tough people do. - Robert H. Schuller",
    "Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
    "Hope is a waking dream. - Aristotle",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Setting goals is the first step in turning the invisible into the visible. - Tony Robbins",
    "Quality is not an act, it is a habit. - Aristotle",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Knowing yourself is the beginning of all wisdom. - Aristotle",
    "Change is the end result of all true learning. - Leo Buscaglia",
    "A goal without a plan is just a wish. - Antoine de Saint-Exupéry",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will. - Vince Lombardi",
    "The best preparation for tomorrow is doing your best today. - H. Jackson Brown, Jr.",
    "If you can dream it, you can do it. - Walt Disney",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Someone is sitting in the shade today because someone planted a tree a long time ago. - Warren Buffett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Don't let it stop you. Failure builds character. - Unknown",
    "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. - Steve Jobs",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. - Mohnish Pabrai",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
    "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
    "We generate fears while we sit. We overcome them by action. - Dr. Henry Link",
    "Whether you think you can or think you can't, you're right. - Henry Ford",
    "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
    "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Creativity is intelligence having fun. - Albert Einstein",
    "What you lack in talent can be made up with desire, hustle and giving 110% all the time. - Don Zimmer",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "Develop an 'attitude of gratitude'. Say thank you to everyone you meet for everything they do for you. - Brian Tracy",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "To see what is right and not do it is a lack of courage. - Confucius",
    "Reading is to the mind, as exercise is to the body. - Brian Tracy",
    "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality. - Brian Tracy",
    "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
    "For every reason it's not possible, there are hundreds of people who have faced the same circumstances and succeeded. - Jack Canfield",
    "Things work out best for those who make the best of how things work out. - John Wooden",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time. - Michael Phelps",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals. - Michelle Obama",
    "Today's accomplishments were yesterday's impossibilities. - Robert H. Schuller",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "If you tell the truth, you don't have to remember anything. - Mark Twain",
    "A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "We accept the love we think we deserve. - Stephen Chbosky",
    "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
    "We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde",
    "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. - Neil Gaiman",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bil Keane",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "The opposite of love is not hate, it's indifference. - Elie Wiesel",
    "A lack of transparency results in distrust and a deep sense of insecurity. - Dalai Lama",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "If you can't explain it to a six year old, you don't understand it yourself. - Albert Einstein",
    "It is never too late to be what you might have been. - George Eliot",
    "Everything you can imagine is real. - Pablo Picasso",
    "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "When you want something, all the universe conspires in helping you to achieve it. - Paulo Coelho",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "Pain is inevitable. Suffering is optional. - Haruki Murakami",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "Simplicity is the ultimate sophistication. - Leonardo da Vinci",
    "He who conquers himself is the mightiest warrior. - Confucius",
    "Try not to become a man of success, but rather become a man of value. - Albert Einstein",
    "One child, one teacher, one book, one pen can change the world. - Malala Yousafzai",
    "The mind is everything. What you think you become. - Buddha",
    "An unexamined life is not worth living. - Socrates",
    "Eighty percent of success is showing up. - Woody Allen",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Winning isn't everything, it's the only thing. - Vince Lombardi",
    "Every child is an artist. The problem is how to remain an artist once he grows up. - Pablo Picasso",
    "You have to learn the rules of the game. And then you have to play better than anyone else. - Albert Einstein",
    "Look deep into nature, and then you will understand everything better. - Albert Einstein",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "Logic will get you from A to B. Imagination will take you everywhere. - Albert Einstein",
    "The true sign of intelligence is not knowledge but imagination. - Albert Einstein",
    "Peace begins with a smile. - Mother Teresa",
    "If you judge people, you have no time to love them. - Mother Teresa",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    "A winner is a dreamer who never gives up. - Nelson Mandela",
    "Education is the most powerful weapon which you can use to change the world. - Nelson Mandela",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "The weak can never forgive. Forgiveness is the attribute of the strong. - Mahatma Gandhi",
    "An eye for an eye only ends up making the whole world blind. - Mahatma Gandhi",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "Happiness is when what you think, what you say, and what you do are in harmony. - Mahatma Gandhi",
    "You must not lose faith in humanity. Humanity is an ocean; if a few drops of the ocean are dirty, the ocean does not become dirty. - Mahatma Gandhi",
    "Freedom is not worth having if it does not include the freedom to make mistakes. - Mahatma Gandhi",
    "Nobody can hurt me without my permission. - Mahatma Gandhi",
    "The future depends on what you do today. - Mahatma Gandhi",
    "The best way to find yourself is to lose yourself in the service of others. - Mahatma Gandhi",
    "To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great. - Mark Twain",
    "Kindness is the language which the deaf can hear and the blind can see. - Mark Twain",
    "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "I hated every minute of training, but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.’ - Muhammad Ali",
    "Service to others is the rent you pay for your room here on earth. - Muhammad Ali",
    "Float like a butterfly, sting like a bee. - Muhammad Ali",
    "It isn’t the mountains ahead to climb that wear you out; it’s the pebble in your shoe. - Muhammad Ali",
    "A man who has no imagination has no wings. - Muhammad Ali",
    "He who is not courageous enough to take risks will accomplish nothing in life. - Muhammad Ali",
    "I am the greatest, I said that even before I knew I was. - Muhammad Ali",
    "Impossible is just a big word thrown around by small men who find it easier to live in the world they’ve been given than to explore the power they have to change it. - Muhammad Ali",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Don’t let the noise of others’ opinions drown out your own inner voice. - Steve Jobs",
    "Stay hungry, stay foolish. - Steve Jobs",
    "Creativity is just connecting things. - Steve Jobs",
    "Innovation distinguishes between a leader and a follower. - Steve Jobs",
    "Be a yardstick of quality. Some people aren't used to an environment where excellence is expected. - Steve Jobs",
    "Design is not just what it looks like and feels like. Design is how it works. - Steve Jobs",
    "I want to put a ding in the universe. - Steve Jobs",
    "My favorite things in life don't cost any money. It's really clear that the most precious resource we all have is time. - Steve Jobs",
    "You can't connect the dots looking forward; you can only connect them looking backward. - Steve Jobs",
    "Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. - Steve Jobs",
    "Sometimes life hits you in the head with a brick. Don't lose faith. - Steve Jobs",
    "That’s been one of my mantras — focus and simplicity. Simple can be harder than complex. - Steve Jobs",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
    "Being the richest man in the cemetery doesn’t matter to me. Going to bed at night saying we’ve done something wonderful, that’s what matters to me. - Steve Jobs",
    "Quality is more important than quantity. One home run is much better than two doubles. - Steve Jobs",
    "I’m convinced that about half of what separates successful entrepreneurs from the non-successful ones is pure perseverance. - Steve Jobs",
    "The people who are crazy enough to think they can change the world are the ones who do. - Steve Jobs",
    "We don’t get a chance to do that many things, and everyone should be really excellent. Because this is our life. - Steve Jobs",
    "Details matter, it’s worth waiting to get it right. - Steve Jobs",
    "Technology is nothing. What's important is that you have a faith in people, that they're basically good and smart, and if you give them tools, they'll do wonderful things with them. - Steve Jobs",
    "Be water, my friend. - Bruce Lee",
    "Knowing is not enough, we must apply. Willing is not enough, we must do. - Bruce Lee",
    "Mistakes are always forgivable, if one has the courage to admit them. - Bruce Lee",
    "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times. - Bruce Lee",
    "If you spend too much time thinking about a thing, you’ll never get it done. - Bruce Lee",
    "A goal is not always meant to be reached, it often serves simply as something to aim at. - Bruce Lee",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. - Bruce Lee",
    "As you think, so shall you become. - Bruce Lee",
    "Adapt what is useful, reject what is useless, and add what is specifically your own. - Bruce Lee",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "Real living is living for others. - Bruce Lee",
    "To hell with circumstances; I create opportunities. - Bruce Lee",
    "The more we value things, the less we value ourselves. - Bruce Lee",
    "If you love life, don't waste time, for time is what life is made up of. - Bruce Lee",
    "Always be yourself, express yourself, have faith in yourself, do not go out and look for a successful personality and duplicate it. - Bruce Lee",
    "Showing off is the fool’s idea of glory. - Bruce Lee",
    "Preparation for tomorrow is hard work today. - Bruce Lee",
    "It's not what you give, it's how you give it. - Bruce Lee",
    "Obey the principles without being bound by them. - Bruce Lee",
    "Knowledge will give you power, but character respect. - Bruce Lee"
]
