quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "We can only see a short distance ahead, but we can see plenty there that needs to be done. - Alan Turing",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Dream big and dare to fail. - Norman Vaughan",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "The best way to predict the future is to create it. - Peter Drucker",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Act as if what you do makes a difference. It does. - William James",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Great things are done by a series of small things brought together. - Vincent Van Gogh",
    "The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Don't stop when you're tired. Stop when you're done. - Unknown",
    "Wake up with determination. Go to bed with satisfaction. - Unknown",
    "Do something today that your future self will thank you for. - Unknown",
    "Little things make big days. - Unknown",
    "It’s going to be hard, but hard does not mean impossible. - Unknown",
    "Don’t wait for opportunity. Create it. - Unknown",
    "Sometimes we’re tested not to show our weaknesses, but to discover our strengths. - Unknown",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "Dream it. Believe it. Build it. - Unknown",
    "Motivation is what gets you started. Habit is what keeps you going. - Jim Ryun",
    "A river cuts through rock, not because of its power, but because of its persistence. - Jim Watkins",
    "Energy and persistence conquer all things. - Benjamin Franklin",
    "Perseverance is not a long race; it is many short races one after the other. - Walter Elliot",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. - Unknown",
    "If you are working on something that you really care about, you don’t have to be pushed. The vision pulls you. - Steve Jobs",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "Failure will never overtake me if my determination to succeed is strong enough. - Og Mandino",
    "Entrepreneurs are great at dealing with uncertainty and also very good at minimizing risk. - Mohnish Pabrai",
    "We may encounter many defeats but we must not be defeated. - Maya Angelou",
    "Knowing is not enough; we must apply. Wishing is not enough; we must do. - Johann Wolfgang Von Goethe",
    "Imagine your life is perfect in every respect; what would it look like? - Brian Tracy",
    "We generate fears while we sit. We overcome them by action. - Dr. Henry Link",
    "Whether you think you can or think you can’t, you’re right. - Henry Ford",
    "Security is mostly a superstition. Life is either a daring adventure or nothing. - Helen Keller",
    "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Creativity is intelligence having fun. - Albert Einstein",
    "What you lack in talent can be made up with desire, hustle and giving 110% all the time. - Don Zimmer",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "Develop an 'attitude of gratitude'. Say thank you to everyone you meet for everything they do for you. - Brian Tracy",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "To see what is right and not do it is a lack of courage. - Confucius",
    "Reading is to the mind, as exercise is to the body. - Brian Tracy",
    "Fake it until you make it! Act as if you had all the confidence you require until it becomes your reality. - Brian Tracy",
    "The future belongs to the competent. Get good, get better, be the best! - Brian Tracy",
    "For every reason it’s not possible, there are hundreds of people who have faced the same circumstances and succeeded. - Jack Canfield",
    "Things work out best for those who make the best of how things work out. - John Wooden",
    "A room without books is like a body without a soul. - Marcus Tullius Cicero",
    "I think goals should never be easy, they should force you to work, even if they are uncomfortable at the time. - Michael Phelps",
    "One of the lessons that I grew up with was to always stay true to yourself and never let what somebody else says distract you from your goals. - Michelle Obama",
    "Today’s accomplishments were yesterday’s impossibilities. - Robert H. Schuller",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "Be the change that you wish to see in the world. - Mahatma Gandhi",
    "If you tell the truth, you don't have to remember anything. - Mark Twain",
    "A friend is someone who knows all about you and still loves you. - Elbert Hubbard",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Always forgive your enemies; nothing annoys them so much. - Oscar Wilde",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
    "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that. - Martin Luther King Jr.",
    "Without music, life would be a mistake. - Friedrich Nietzsche",
    "We accept the love we think we deserve. - Stephen Chbosky",
    "Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring. - Marilyn Monroe",
    "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle. - Albert Einstein",
    "We are all in the gutter, but some of us are looking at the stars. - Oscar Wilde",
    "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. - Neil Gaiman",
    "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. - Bil Keane",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "The opposite of love is not hate, it's indifference. - Elie Wiesel",
    "A lack of transparency results in distrust and a deep sense of insecurity. - Dalai Lama",
    "Happiness is not something ready made. It comes from your own actions. - Dalai Lama",
    "If you can't explain it to a six year old, you don't understand it yourself. - Albert Einstein",
    "It is never too late to be what you might have been. - George Eliot",
    "Everything you can imagine is real. - Pablo Picasso",
    "Life isn't about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "When you want something, all the universe conspires in helping you to achieve it. - Paulo Coelho",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "It is during our darkest moments that we must focus to see the light. - Aristotle",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "In the middle of every difficulty lies opportunity. - Albert Einstein",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "Pain is inevitable. Suffering is optional. - Haruki Murakami",
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost"
]
